### PR TITLE
Send status

### PR DESCRIPTION
**Pull request by dancaron**
Notes: 

I think the function flip_bytes_format_send is useful because it builds a reliable byte string suitable for RFxmit. A lot of the modules I tried seemed to produce some byte math that I'm not certain would be appropriate for rfcat. I could be wrong about this, but it's something you might want to investigate.

### CODE REVIEW

**Comment by ps2** [comment]
packet.py consumes and provides strings of binary data, which is what RFCat consumes and provides as well.  I think this function: https://github.com/openaps/openomni/blob/craft-status/openomni/packet.py#L56-L59 handles flipping bytes for that kind of data correctly; or at least I haven't seen any issues with it. I may be missing something, of course.

I'd like to keep a single place for byte flipping if we can.  If you want to use flip_bytes_format_send, let's talk; I have no special attachment to the code I linked to above; just trying to keep things simple.

**Comment by ps2** [comment]
LGTM!  I'll have some changes as discussed in my next PR, but this looks like a good command interface for generating packets. Thanks!

**Comment by dancaron** [comment]
I'm all for avoiding duplication. And I'm happy to use your flip_bytes function. It's a lot more idiomatic, and you are getting the 1d18 packet. Just keep this in mind down the road should we hit something questionable with TX. Although it seems we have it mostly ironed out.

**Comment by danamlewis** [comment]
Just commenting to test Slack integration. (1)

**Pull request merged**
